repo_name: "Echo Messenger"
repo_icon: "icon.png"
repo_description: >
  A highly fault-tolerant, zero-server E2EE messenger engineered for absolute communication resilience. 
  Supports standard P2P, robust anti-DPI tunneling, and offline mesh networking (WiFi NAN, BLE, LoRa hardware).

repo_url: "https://theravanz.github.io/echo-fdroid-repo/repo"

# Локальный путь к Android SDK для сборщика индексов
sdk_path: "/home/ravanz/Android/Sdk"

# Настройки приватного ключа подписи репозитория (генерируются автоматически)
keystore: "keystore.p12"
repo_keyalias: "default"

# Базовые параметры безопасности и очистки
clean_cache: false
keydname: CN=default, OU=F-Droid
keystorepass: k6WWO99VPsF7wknp5bVFyHbdpDnBbNmaJGjuzpHTuVw=
keypass: k6WWO99VPsF7wknp5bVFyHbdpDnBbNmaJGjuzpHTuVw=
